### ISSUE TITLE
Page formatting

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#23]
Can all the content on the page line up with the end of the orange line at the top.

I have used the case studies page as an example:

This is the site currently:

![ecovend-case-studies_current](https://user-images.githubusercontent.com/40568273/68188718-b26fce00-ffa1-11e9-8da5-8931815b3741.png)

I would like it as below please (on every page)
![ecovend-case-studies_new-formatting](https://user-images.githubusercontent.com/40568273/68188742-bf8cbd00-ffa1-11e9-91b3-6b89cbef7dfc.png)

I would like this to be the same on all pages - so that page title are always in the same place on each page too, all the content aligns with edge of orange line either side (left and right)

<img width="686" alt="Screenshot 2019-11-05 07 57 20" src="https://user-images.githubusercontent.com/40568273/68188846-fc58b400-ffa1-11e9-97c6-b99827cbb134.png">

**Comment by kpierduta** [comment]
Could the questions be lined up on the left-hand side and can this be the same font size as the rest of the site and orange in colour - I have print screened size example from home page.

<img width="1141" alt="Screenshot 2019-11-05 07 59 09" src="https://user-images.githubusercontent.com/40568273/68188917-2f9b4300-ffa2-11e9-8e98-3bb953ac2259.png">

<img width="879" alt="Screenshot 2019-11-05 08 00 24" src="https://user-images.githubusercontent.com/40568273/68188987-58bbd380-ffa2-11e9-9956-2530f4497a2c.png">

**Comment by gagansaini1212** [comment]
@kpierduta have a review on the website again. Let me know if there are any fixes.
