### ISSUE TITLE
Infographic section - editable

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#24]
I need this section to be editable so that they can add points on all case study pages whenever a client adds a new one. I am happy for just to change the design slightly if need be:

<img width="843" alt="Screenshot 2019-11-05 08 02 04" src="https://user-images.githubusercontent.com/40568273/68189125-a5071380-ffa2-11e9-83da-45bc22d710a2.png">

https://eco-vend.netlify.com/case-study

**Comment by gagansaini1212** [comment]
@kpierduta In what manner points will be displayed?

**Comment by kpierduta** [comment]
@gagansaini1212 
They will be sentences that fit into the shapes
Editable via Contentful

**Comment by gagansaini1212** [comment]
@kpierduta like similar stuff but we have four sections
![Screenshot 2019-11-05 at 3 42 41 PM](https://user-images.githubusercontent.com/35168573/68198931-04851380-ffe3-11e9-8671-c11a2f1977c9.png)

**Comment by kpierduta** [comment]
@gagansaini1212 if we can pop those into orange circles with white text that could work?

**Comment by gagansaini1212** [comment]
@kpierduta okay working on it and send you the build after complete

**Comment by gagansaini1212** [comment]
@kpierduta Have a review is it fine or you want some changes?
![Screenshot 2019-11-05 at 5 04 55 PM](https://user-images.githubusercontent.com/35168573/68204670-8af32280-ffee-11e9-8e54-d34735ad9abe.png)

**Comment by kpierduta** [comment]
Hey @gagansaini1212 it's looking good, is it possible to add these details above?

![infographic](https://user-images.githubusercontent.com/40568273/68205573-8c0e5a80-ffc2-11e9-90c8-4c95850bef9f.jpg)
