### ISSUE TITLE
Contact form changes (global)

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#32]
Please reduce spacing in contact form perhaps make it look smaller and more balanced with the our address section. Add a 'get in touch to find out more’ above the submission box on the footer.

Across all instances of contact section.

Please see guide design:

<img width="885" alt="Screenshot 2019-11-25 16 00 59" src="https://user-images.githubusercontent.com/40568273/69556548-c99c4d00-0f9c-11ea-96ef-653ba81a8169.png">

[contact-form-changes.pdf](https://github.com/zeiq-co/ecovend-reverse-vending/files/3887460/contact-form-changes.pdf)

**Comment by kpierduta** [comment]
The contact forms have lost the blue #E2EFF2 background surrounding them. If we can just pop this back in.

![Screenshot 2019-12-04 10 18 06](https://user-images.githubusercontent.com/40568273/70134219-8c604b00-167f-11ea-8fdc-d444ebca041c.png)

**Comment by gagansaini1212** [comment]
background-color popped up now

**Comment by kpierduta** [comment]
@gagansaini1212 it is popping up on home and contact page for me but not on the others, might be my cache though?
