### ISSUE TITLE
Change link to anchor link

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#33]
On the homepage: https://eco-vend.netlify.com/
Can the link 'Contact' so that it scrolls to the contact form at the bottom of the home page instead of taking people to the contact page.

![Screenshot 2019-11-27 16 11 41](https://user-images.githubusercontent.com/40568273/69740077-ac988300-1130-11ea-8a2e-e4e96e8f083c.png)

**Comment by gagansaini1212** [comment]
@kpierduta fixnow
