### ISSUE TITLE
Change text size - Advertising page

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#34]
https://eco-vend.netlify.com/advertising

The client does not want the text to be a title, can this just be the same as the text below except bold.

![Screenshot 2019-11-27 16 30 18](https://user-images.githubusercontent.com/40568273/69741589-3c3f3100-1133-11ea-949b-52006caaa1b6.png)

**Comment by gagansaini1212** [comment]
@kpierduta could you please mention the font-size required and other properties like line-height?

**Comment by gagansaini1212** [comment]
@kpierduta close this issue after cross-check I think Kunal fixed this issue already.

**Comment by kpierduta** [comment]
@gagansaini1212 I just want the writing to be the same as the paragraph below so the one that starts "Our Ecovend RVMs..."  except in bold.

**Comment by gagansaini1212** [comment]
please check this once. All good?

**Comment by kpierduta** [comment]
@gagansaini1212 brilliant thank you
