### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#36]
The client would like the website to have a margin:

![Page margin problem](https://user-images.githubusercontent.com/40568273/69808837-626eda80-11e0-11ea-8901-fb2478a5f3b3.PNG)

Can we have this so the padding on the left is consistent, so content/logos/text starts at the same alignment.

E.g. the example below the questions and answers to not start at the same point on the left.

![Screenshot 2019-11-27 16 56 49](https://user-images.githubusercontent.com/40568273/69743926-27fd3300-1137-11ea-9478-58c525c3cf99.png)

**Comment by kpierduta** [comment]
The alignment is still out and padding as per client's request has not been added

<img width="321" alt="Screenshot 2019-12-02 13 07 16" src="https://user-images.githubusercontent.com/40568273/69961853-ac1f3400-1504-11ea-9a76-6dd2dc54351e.png">

**Comment by gagansaini1212** [comment]
@kpierduta please check FAQs page alignment now fixed

**Comment by kpierduta** [comment]
Thank you

**Comment by kpierduta** [comment]
1. Since publishing the edits, the page titles are not in the same place on each page.
2. OurRange should be Our Range
3. Can we make sure that the content has the same padding on the left hand side - from the screenshot you will see that the content starts further to the left than the title.

<img width="425" alt="Screenshot 2019-12-03 11 28 34" src="https://user-images.githubusercontent.com/40568273/70047555-31b3ea00-15c0-11ea-9f38-d803a39037aa.png">

<img width="392" alt="Screenshot 2019-12-03 11 28 45" src="https://user-images.githubusercontent.com/40568273/70047557-31b3ea00-15c0-11ea-88fe-a83d2f6902a9.png">

<img width="485" alt="Screenshot 2019-12-03 11 28 39" src="https://user-images.githubusercontent.com/40568273/70047559-31b3ea00-15c0-11ea-8de3-117889b1fe40.png">

**Comment by gagansaini1212** [comment]
commit changes. Please check all headings are at same position

**Comment by kpierduta** [comment]
@gagansaini1212  great thank you
