### ISSUE TITLE
Image change across site

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#37]
Can we change all instances of this image to the one attached at the bottom please (with the red and green chutes on).

It's on:
https://eco-vend.netlify.com/
https://eco-vend.netlify.com/advertising
https://eco-vend.netlify.com/our-range (bottom product)

![Screenshot 2019-11-28 13 12 05](https://user-images.githubusercontent.com/40568273/69808982-af52b100-11e0-11ea-9a6b-abf0a63ecfa8.png)

Change to this one:
![Embedded RVM Machine_GRChutes](https://user-images.githubusercontent.com/40568273/69809068-e1641300-11e0-11ea-9ae9-781c146f64b7.jpg)

**Comment by gagansaini1212** [comment]
These images are coming from contentful. @iamkunall and @kpierduta you can change from there.

**Comment by gagansaini1212** [comment]
@kpierduta if you want e to change then please provide me contentful access. My email is gagansaini1212@gmail.com

**Comment by kpierduta** [comment]
@gagansaini1212 I have just re-published this as the size was too big, could you push the changes to hosting so I can just double check it is the right size now, please? Thank you
