### ISSUE TITLE
Homepage red section

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#44]
**Client feedback:**
"Currently the red ‘why choose reverse vending is no a full ‘page height’ can we make this a bit taller so that it fits the page break to page break better or if you like change the design to something that works better. I just don’t think it looks right as it is at the moment."

![Screenshot 2019-11-28 14 14 01](https://user-images.githubusercontent.com/40568273/69813163-90a4e800-11e9-11ea-839d-39ae24aedc3e.png)

Solution:
I'm thinking you just add padding above and below so red section is bigger? 
@perminder-klair what do you think?

**Comment by gagansaini1212** [comment]
@kpierduta added padding to this section and closing this issue.
