### ISSUE TITLE
Section not in Contentful

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#49]
https://eco-vend.netlify.com/advertising

Can you let me know where I can access this in Contentful to change content errors, please?

<img width="1193" alt="Screenshot 2019-12-02 13 00 40" src="https://user-images.githubusercontent.com/40568273/69961439-c6a4dd80-1503-11ea-92be-29bb7bd1e367.png">

Are the other elements on this page also editable in Contentful?

<img width="1186" alt="Screenshot 2019-12-02 13 02 54" src="https://user-images.githubusercontent.com/40568273/69961590-15eb0e00-1504-11ea-9899-d98ddcf87f56.png">
<img width="1201" alt="Screenshot 2019-12-02 13 03 01" src="https://user-images.githubusercontent.com/40568273/69961591-1683a480-1504-11ea-9966-8cb7fcccc3a7.png">

**Comment by gagansaini1212** [comment]
@kpierduta I don't know about contentful fields. As I don't have access to contentful.

**Comment by kpierduta** [comment]
@gagansaini1212 I have invited you now
