### ISSUE TITLE
Our Range & Product Pages

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#52]
The client wants to split product pages into individual pages and have the 'Our range' page an overview.

I have created the template pages as below.

The table layouts must be able to be edited by the client in Contentful.

![1-product-page-overview](https://user-images.githubusercontent.com/40568273/71663445-2bdf2f00-2d4d-11ea-820f-f310aa4124e5.jpg)

![1-individual-product-page](https://user-images.githubusercontent.com/40568273/71663456-36012d80-2d4d-11ea-819a-24aad656f6f4.jpg)

[1-product-page-overview.pdf](https://github.com/zeiq-co/ecovend-reverse-vending/files/4015607/1-product-page-overview.pdf)
[Uploading 1-individual-product-page.pdf…]()

**Comment by gagansaini1212** [comment]
@kpierduta let me know if we will follow the above design then I will add fields to the contentful accordingly.

**Comment by kpierduta** [comment]
Hey @gagansaini1212 I will let you know as soon as I hear from client, the only thing that will be different is if we split the 3 onto 3 separate pages but the table design and layout will be the same

**Comment by gagansaini1212** [comment]
@kpierduta Yes, we can. But let me know after client's confirmation. It will save our effort.

**Comment by kpierduta** [comment]
![Screenshot 2020-01-20 11 10 07](https://user-images.githubusercontent.com/40568273/72722084-6c281500-3b75-11ea-89f5-1e3af76b8497.png)

@iamkunall 
Looking great, the only thing now is that the boxes need a box around them and the EcoVend tag (grey background white text needs adding (as per the design - I have re-screenshot below)

<img width="553" alt="Screenshot 2020-01-20 11 11 01" src="https://user-images.githubusercontent.com/40568273/72722148-8eba2e00-3b75-11ea-91f9-67e20f0a5398.png">
