### ISSUE TITLE
Change infographic

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#62]
Client feedback:
![image](https://user-images.githubusercontent.com/40568273/71669204-cc404e00-2d63-11ea-8a1c-2ce520e6f95a.png)

![image](https://user-images.githubusercontent.com/40568273/71669216-d7937980-2d63-11ea-8142-6b8be86822fb.png)

Can you do like this one but in orange brand colour?
![stock-vector-vector-infographic-label-design-template-with-icons-and-options-or-steps-can-be-used-for-1192868500](https://user-images.githubusercontent.com/40568273/71669365-5a1c3900-2d64-11ea-8c6f-776236c10937.jpg)

**Comment by iamkunall** [comment]
@kpierduta  the images you provide are not equal in size. Provide the images again

**Comment by kpierduta** [comment]
@iamkunall I'm sorry, let me know if these are okay? 

![infographic-blocks_block1](https://user-images.githubusercontent.com/40568273/72563060-c8a0e100-38a4-11ea-934f-ea76a9c8e6ac.png)

![infographic-blocks_block2](https://user-images.githubusercontent.com/40568273/72563061-c8a0e100-38a4-11ea-8c7f-f900d1662716.png)

![infographic-blocks_block3](https://user-images.githubusercontent.com/40568273/72563062-c8a0e100-38a4-11ea-9631-138b9a8a5d05.png)

![infographic-blocks_block4](https://user-images.githubusercontent.com/40568273/72563063-c8a0e100-38a4-11ea-86db-c7a8bf2a9e34.png)

**Comment by kpierduta** [comment]
@iamkunall can we copy the example where by we can upload an icon in this space and the title text is bigger, put any icon in for now, just for example purposes :) you are star, thank you for all your hard work as always

**Comment by kpierduta** [comment]
@iamkunall  strangely the red block is wider on here - I checked the image files I sent and they are all the same width, so not sure if something strange is going on?

<img width="1226" alt="Screenshot 2020-01-18 18 11 42" src="https://user-images.githubusercontent.com/40568273/72668395-18ef7e80-3a1e-11ea-9f6d-1af5311365d0.png">

**Comment by iamkunall** [comment]
@kpierduta  this is issue with only the red block i think this is because they don't have any arrow sign
.

**Comment by kpierduta** [comment]
@iamkunall 

The client now wants 3 orange circles. 

Put in the below statements into the circles, centre justify the copy in these circles

Change the rectangle boxes to orange circles as below ( without the icons obviously)

![image](https://user-images.githubusercontent.com/40568273/73668662-18055080-469e-11ea-8d68-0e8764472f0f.png)

RVMs start from only £200 per which can be offset by advertising revenue

59% of customers expect companies to make a stand on climate and environmental issues

Large Integral Audio-Video Screen And Light Box Panels For Instant Revenue From Branding And Advertising

**Comment by kpierduta** [comment]
@iamkunall

It should be only 3 circles and they should contain the below information:

RVMs start from only £200 per which can be offset by advertising revenue

59% of customers expect companies to make a stand on climate and environmental issues

Large Integral Audio-Video Screen And Light Box Panels For Instant Revenue From Branding And Advertising
