### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#63]
Can we make sure that the fonts used are Abadi only.

So font to be abadi light
and titles to be abadi regular

**Comment by kpierduta** [comment]
Hi @iamkunall I have added all the amendments from the client now for this

**Comment by kpierduta** [comment]
@iamkunall 

Please can you check title fonts in the contact form as they look different

<img width="1177" alt="Screenshot 2020-01-20 11 16 05" src="https://user-images.githubusercontent.com/40568273/72722467-4bac8a80-3b76-11ea-9dfb-aed79aa5f6a4.png">

Please match them with this font style:
<img width="803" alt="Screenshot 2020-01-20 11 16 10" src="https://user-images.githubusercontent.com/40568273/72722477-536c2f00-3b76-11ea-8433-23fa534e56a9.png">

**Comment by iamkunall** [comment]
@kpierduta  have a look again
