### ISSUE TITLE
Our Range menu structure change

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#75]
Add individual pages to drop down menu,

- [x] And change Our Range menu title to Products

- [x] Add individual pages as drop down secondary menu. 

So

Products
RVM 100/200
RVM 400
RVM 500

**Comment by kpierduta** [comment]
@iamkunall 

Use of capitals consistency - change it to say RVM-400 instead of Rvm-400 so that it matches the other 2 pages

<img width="518" alt="Screenshot 2020-02-04 15 56 15" src="https://user-images.githubusercontent.com/40568273/73761526-e5735a80-4766-11ea-98b1-f99af159020f.png">

**Comment by iamkunall** [comment]
@kpierduta fix for now
