### ISSUE TITLE
Blog page - share and next post section

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/ecovend-reverse-vending#77]
- [x] These sections need to pull next post and be able to share links

<img width="1078" alt="Screenshot 2020-02-03 10 59 48" src="https://user-images.githubusercontent.com/40568273/73647953-7289b700-4674-11ea-834a-250b8cac318a.png">

- [x] Remove the ‘recent posts’ section from sidebar
- [x] Please ensure that images are correctly sized

**Comment by kpierduta** [comment]
@iamkunall Twitter is working but Facebook share is throwing an error back

<img width="596" alt="Screenshot 2020-02-04 16 05 08" src="https://user-images.githubusercontent.com/40568273/73762937-ac3bea00-4768-11ea-8681-8de214ff0556.png">

**Comment by kpierduta** [comment]
@iamkunall 

- [ ] Distorted images on the news thumbnails - I have resized square images for you as Contentful is not set up currently. I want it to keep the image on the page as it is but have these on the preview.

![facilities-show-2-100](https://user-images.githubusercontent.com/40568273/73766553-1a36e000-476e-11ea-94b2-9548ec89cf20.jpg)
![terminator-100](https://user-images.githubusercontent.com/40568273/73766554-1a36e000-476e-11ea-90a9-34ad9d4cf4f2.jpg)
![interview-100](https://user-images.githubusercontent.com/40568273/73766555-1a36e000-476e-11ea-80e7-d7153d0524bc.jpg)
![brakes-100](https://user-images.githubusercontent.com/40568273/73766557-1acf7680-476e-11ea-8cdf-f345cf43dc79.jpg)
![expo-live-news-100](https://user-images.githubusercontent.com/40568273/73766558-1acf7680-476e-11ea-8a75-f6d790738db3.jpg)
![expo-live-100](https://user-images.githubusercontent.com/40568273/73766559-1acf7680-476e-11ea-83c3-40bc4d978fca.jpg)
![lima2019-100](https://user-images.githubusercontent.com/40568273/73766560-1acf7680-476e-11ea-8e0c-f316b3315845.jpg)
![rvm400-100](https://user-images.githubusercontent.com/40568273/73766562-1acf7680-476e-11ea-8108-b884d11ceafb.jpg)
![letchworth-100](https://user-images.githubusercontent.com/40568273/73766564-1b680d00-476e-11ea-8b0a-a6b061d82149.jpg)
![facilities-show-100](https://user-images.githubusercontent.com/40568273/73766567-1b680d00-476e-11ea-8a88-db50228070e8.jpg)
![bbc-news-100](https://user-images.githubusercontent.com/40568273/73766568-1b680d00-476e-11ea-8f6d-3b0d8f1b8262.jpg)

**Comment by iamkunall** [comment]
@kpierduta  can you explain what you want to do with these images
